[package]
name = "ugit"
version = "0.1.0"
authors = ["Simon Morgan <sjm@sjm.io>"]
edition = "2018"

[dependencies]
clap = { version = "4", features = ["cargo"] }
sha-1 = "0.9"
tempfile = "3"
walkdir = "2"
